apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: gitlab
  labels:
    name: minio
    app: minio
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - name: http
    port: 9000
    protocol: TCP
rancher@m1:~/kubernetes-gitlab> cat minio/minio-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: gitlab
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        name: minio
        app: minio
    spec:
      containers:
      - name: minio
        image: bitnami/minio:2023.10.16-debian-11-r0
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: data-store
          mountPath: /export
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
      volumes:
      - name: data-store
        emptyDir: {}
