apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: gitlab
  labels:
    name: minio
    app: minio
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - name: http
    port: 9000
    protocol: TCP
